### ISSUE TITLE
Update StableV2V

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [wentianli/awesome-video-editing#2]
Hi @wentianli ,

Thank you for the amazing repository! I believe that this great work would significantly contribute to the community.

I wonder if you could update our work StableV2V in our PR? I have updated the links of the [arXiv paper](https://arxiv.org/pdf/2411.11045) and [our project page](https://alonzoleeeooo.github.io/StableV2V) following your template. We would highly appreciate it if you could accept.

Also, there are some additional information about our work, i.e., [our code repository](https://github.com/AlonzoLeeeooo/StableV2V) and [a curated testing benchmark named DAVIS-Edit](https://huggingface.co/datasets/AlonzoLeeeooo/DAVIS-Edit). Feel free to refer to them if you need the information.

Please do not hesitate to let me know if there is anything that I need to modify in the proposed PR. Looking forward to your reply!

Best,
Chang

**Comment by wentianli** [comment]
Sorry for my late response. This is indeed a great work. However it might not fall into the realm of this repo, which mainly focuses on the cinematographic aspects of video editing and arrangement.
Thank you for your interest, I really appreciate it.

**Comment by AlonzoLeeeooo** [comment]
Thanks for replying! I understand and agree with you that this work does not fit the repo quite well. It doesn't matter.
Wish you obtaining further success in your research career!

Best
